name: Automated Issue Triage

on:
  issues:
    types:
      - labeled

jobs:
  triage:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run triage script
        run: node .github/scripts/triage.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
